export const social = [
  {
    value: "github",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/github.svg",
    link: "",
    link_placeholder: "https://github.com/",
    placeholder: "github username",
  },
  {
    value: "twitter",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/twitter.svg",
    link: "",
    link_placeholder: "https://twitter.com/",
    placeholder: "twitter username",
  },
  {
    value: "linkedin",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/linkedin.svg",
    link: "",
    link_placeholder: "",
    placeholder: "Enter linkedin link",
  },
  {
    value: "dev.to",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/dev-dot-to.svg",
    link: "",
    link_placeholder: "https://dev.to/",
    placeholder: "dev.to username",
  },
  {
    value: "hashnode",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/hashnode.svg",
    link: "",
    link_placeholder: "https://hashnode.com/",
    placeholder: "hashnode username",
  },
  {
    value: "youtube",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/youtube.svg",
    link: "",
    link_placeholder: "https://www.youtube.com/c",
    placeholder: "youtube channel name",
  },
  {
    value: "google",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@v6/icons/gmail.svg",
    link: "",
    link_placeholder: "maito:",
    placeholder: "Enter mail id",
  },
  {
    value: "discord",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/discord.svg",
    link: "",
    link_placeholder: "",
    placeholder: "Enter discord link",
  },
  {
    value: "facebook",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/facebook.svg",
    link: "",
    link_placeholder: "https://fb.com/",
    placeholder: "Enter facebook username",
  },
  {
    value: "freecodecamp",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@v6/icons/freecodecamp.svg",
    link: "",
    link_placeholder: "https://www.freecodecamp.org/news/author/",
    placeholder: "freecodecamp username",
  },
  {
    value: "instagram",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/instagram.svg",
    link: "",
    link_placeholder: "https://instagram.com/",
    placeholder: "instagram username",
  },
  {
    value: "reddit",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@v6/icons/reddit.svg",
    link: "",
    link_placeholder: "",
    placeholder: "Enter reddit link",
  },
  {
    value: "slack",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@v6/icons/slack.svg",
    link: "",
    link_placeholder: "",
    placeholder: "Enter slack link",
  },
  {
    value: "stack overflow",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/stackoverflow.svg",
    link: "",
    link_placeholder: "",
    placeholder: "Enter stack-overflow link",
  },
  {
    value: "dribbble",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/dribbble.svg",
    link: "",
    link_placeholder: "",
    placeholder: "Enter dribble link",
  },
  {
    value: "codepen",
    icon: "https://cdn.jsdelivr.net/npm/simple-icons@v6/icons/codepen.svg",
    link: "",
    link_placeholder: "",
    placeholder: "Enter codepen link",
  },
];
