export const social=[
    {
        value:"github",
        label:"github",
        color:"black"
    },
    {
        value:"twitter",
        label:"twitter",
        color:"blue-500"
    },
    {
        value:"linkedin-square",
        label:"linkedin",
        color:"blue-500"
    },
    {
        value:"dev-to",
        label:"dev.to",
        color:"black"
    },
    {
        value:"hashnode",
        label:"hashnode",
        color:"blue-600"
    },
    {
        value:"globe",
        label:"website",
        color:"black"
    },
    {
        value:"youtube-play",
        label:"youtube",
        color:"red-500"
    },
    {
        value:"google",
        label:"gmail",
        color:"red-500"
    },
    {
        value:"discord",
        label:"discord",
        color:"blue-600"
    },
    {
        value:"facebook",
        label:"facebook",
        color:"blue-600"

    },
    {
        value:"free-code-camp",
        label:"freecodecamp",
        color:"black"

    },{
        value:"quora",
        label:"quora",
        color:"red-500"

    },
    {
        value:"instagram",
        label:"instagram",
        color:"red-800"

    },
    {
        value:"reddit",
        label:"reddit",
        color:"red-700"
    },
    {
        value:"slack",
        label:"slack",
        color:"black"
    },
    {
        value:"stack-overflow",
        label:"stack overflow",
        color:"yellow-700"
    },
    {
        value:"dribbble",
        label:"dribbble",
        color:"pink-800"
    },
    {
        value:"codepen",
        label:"codepen",
        color:"black"
    }
]