export const social = [
  {
    value: "github",
    label: "github",
    color: "black",
    link: "",
    link_placeholder: "https://github.com/",
    placeholder: "github username",
  },
  {
    value: "twitter",
    label: "twitter",
    color: "blue-500",
    link: "",
    link_placeholder: "https://twitter.com/",
    placeholder: "twitter username",
  },
  {
    value: "linkedin-square",
    label: "linkedin",
    color: "blue-500",
    link: "",
    link_placeholder: "",
    placeholder: "Enter linkedin link",
  },
  {
    value: "dev-to",
    label: "dev.to",
    color: "black",
    link: "",
    link_placeholder: "https://dev.to/",
    placeholder: "dev.to username",
  },
  {
    value: "hashnode",
    label: "hashnode",
    color: "blue-600",
    link: "",
    link_placeholder: "https://hashnode.com/",
    placeholder: "hashnode username",
  },
  {
    value: "globe",
    label: "website",
    color: "black",
    link: "",
    link_placeholder: "",
    placeholder: "Enter website link",
  },
  {
    value: "youtube-play",
    label: "youtube",
    color: "red-500",
    link: "",
    link_placeholder: "https://www.youtube.com/c",
    placeholder: "youtube channel name",
  },
  {
    value: "google",
    label: "gmail",
    color: "red-500",
    link: "",
    link_placeholder: "maito:",
    placeholder: "Enter mail id",
  },
  {
    value: "discord",
    label: "discord",
    color: "blue-600",
    link: "",
    link_placeholder: "",
    placeholder: "Enter discord link",
  },
  {
    value: "facebook",
    label: "facebook",
    color: "blue-600",
    link: "",
    link_placeholder: "https://fb.com/",
    placeholder: "Enter facebook username",
  },
  {
    value: "free-code-camp",
    label: "freecodecamp",
    color: "black",
    link: "",
    link_placeholder: "https://www.freecodecamp.org/news/author/",
    placeholder: "freecodecamp username",
  },
  {
    value: "instagram",
    label: "instagram",
    color: "red-800",
    link: "",
    link_placeholder: "https://instagram.com/",
    placeholder: "instagram username",
  },
  {
    value: "reddit",
    label: "reddit",
    color: "red-700",
    link: "",
    link_placeholder: "",
    placeholder: "Enter reddit link",
  },
  {
    value: "slack",
    label: "slack",
    color: "black",
    link: "",
    link_placeholder: "",
    placeholder: "Enter slack link",
  },
  {
    value: "stack-overflow",
    label: "stack overflow",
    color: "yellow-700",
    link: "",
    link_placeholder: "",
    placeholder: "Enter stack-overflow link",
  },
  {
    value: "dribbble",
    label: "dribbble",
    color: "pink-800",
    link: "",
    link_placeholder: "",
    placeholder: "Enter dribble link",
  },
  {
    value: "codepen",
    label: "codepen",
    color: "black",
    link: "",
    link_placeholder: "",
    placeholder: "Enter codepen link",
  },
];
