export const social = [
  {
    value: "github",
    link: "",
    link_placeholder: "https://github.com/",
    placeholder: "github username",
    darkPath: true,
  },
  {
    value: "twitter",
    link: "",
    link_placeholder: "https://twitter.com/",
    placeholder: "twitter username",
    darkPath: false,
  },
  {
    value: "linkedin",
    link: "",
    link_placeholder: "",
    placeholder: "Enter linkedin link",
    darkPath: false,
  },
  {
    value: "devto",
    link: "",
    link_placeholder: "https://dev.to/",
    placeholder: "dev.to username",
    darkPath: true,
  },
  {
    value: "hashnode",
    link: "",
    link_placeholder: "https://hashnode.com/@",
    placeholder: "hashnode username",
    darkPath: false,
  },
  {
    value: "youtube",
    link: "",
    link_placeholder: "",
    placeholder: "channel link",
    darkPath: false,
  },
  {
    value: "gmail",
    link: "",
    link_placeholder: "maito:",
    placeholder: "Enter mail id",
    darkPath: false,
  },
  {
    value: "discord",
    link: "",
    link_placeholder: "",
    placeholder: "Enter discord link",
    darkPath: false,
  },
  {
    value: "facebook",
    link: "",
    link_placeholder: "https://fb.com/",
    placeholder: "Enter facebook username",
    darkPath: false,
  },
  {
    value: "freecodecamp",
    link: "",
    link_placeholder: "https://www.freecodecamp.org/news/author/",
    placeholder: "freecodecamp username",
    darkPath: true,
  },
  {
    value: "instagram",
    link: "",
    link_placeholder: "https://instagram.com/",
    placeholder: "instagram username",
    darkPath: false,
  },
  {
    value: "slack",
    link: "",
    link_placeholder: "",
    placeholder: "Enter slack link",
    darkPath: false,
  },
  {
    value: "stackoverflow",
    link: "",
    link_placeholder: "",
    placeholder: "Enter stack-overflow link",
    darkPath: false,
  },
  {
    value: "dribbble",
    link: "",
    link_placeholder: "",
    placeholder: "Enter dribble link",
    darkPath: false,
  },
  {
    value: "codesandbox",
    link: "",
    link_placeholder: "",
    placeholder: "Enter codesandox link",
    darkPath: true,
  },
  {
    value: "codepen",
    link: "",
    link_placeholder: "",
    placeholder: "Enter codepen link",
    darkPath: true,
  },
  {
    value: "twitch",
    link: "",
    link_placeholder: "",
    placeholder: "Enter twitch link",
    darkPath: false,
  },
  {
    value: "medium",
    link: "",
    link_placeholder: "https://medium.com/@",
    placeholder: "Enter medium username",
    darkPath: true,
  },
];
